### ISSUE TITLE
problem anchor

### ISSUE THREAD

**Issue by Link0Darck** [berichan/SysBot.ACNHOrders#16]
Good morning,
I have this problem, can you please help me
thank you in advance

`25/11/2021 18:10:53 [   Error] Command:  Discord.Commands.CommandException: Error occurred executing "setAnchor" for KuroNeko#6775 in Switch Glitch/🏧acnh-glitch🏧.
 ---> System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at SysBot.Base.SwitchSocketAsync.<>c__DisplayClass9_0.<SendAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at SysBot.Base.SwitchSocketAsync.SendAsync(Byte[] buffer, CancellationToken token)
   at SysBot.Base.SwitchSocketAsync.ReadRaw(Byte[] command, Int32 length, CancellationToken token)
   at SysBot.ACNHOrders.DodoPositionHelper.FollowMainPointer(Int64[] jumps, CancellationToken token) in /home/pi/Documents/BOT-ACNH/Bot/Helpers/DodoPositionHelper.cs:line 48
   at SysBot.ACNHOrders.CrossBot.ReadAnchor(CancellationToken token) in /home/pi/Documents/BOT-ACNH/Bot/CrossBot.cs:line 965
   at SysBot.ACNHOrders.CrossBot.UpdateAnchor(Int32 index, CancellationToken token) in /home/pi/Documents/BOT-ACNH/Bot/CrossBot.cs:line 939
   at SysBot.ACNHOrders.AnchorModule.SetAnchorAsync(Int32 anchorId) in /home/pi/Documents/BOT-ACNH/Discord/Modules/AnchorModule.cs:line 16
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---`

https://www.toptal.com/developers/hastebin/koruxesufi.yaml

**Comment by berichan** [comment]
Spam/Abuser
